"use client";

import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCaseLabel, getCaseReference } from "@/lib/case-utils";

type DashboardRequest = { id: string; title: string; status: string; priority: string; customer: { name: string }; updatedAt: Date };
type DashboardTransaction = { id: string; description: string; amount: number; customer: { name: string } | null; type: string };

export function DashboardWorkload({ requests, transactions, metrics }: { requests: DashboardRequest[]; transactions: DashboardTransaction[]; metrics: { customerCount: number; open: number; highPriority: number; unassigned: number; inProgress: number; escalated: number } }) {
  const [visible, setVisible] = useState({ overview: true, priority: true, recent: true, transactions: false });
  const [customizing, setCustomizing] = useState(false);
  const toggle = (key: keyof typeof visible) => setVisible((current) => ({ ...current, [key]: !current[key] }));
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">Customer service operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Support workload</h1><p className="mt-1 text-sm text-muted-foreground">See which customer issues need attention and move them toward resolution.</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><Link href="/portal">View customer portal</Link></Button><Button type="button" variant="outline" size="sm" onClick={() => setCustomizing((value) => !value)}>Customize Dashboard</Button></div></div>
    {customizing ? <Card><CardHeader><CardTitle>Dashboard sections</CardTitle><CardDescription>Choose the information you want in your daily workload view.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-4">{(["overview", "priority", "recent", "transactions"] as const).map((key) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={visible[key]} onChange={() => toggle(key)} />{key === "overview" ? "Case overview" : key === "priority" ? "Priority queue" : key === "recent" ? "Recent cases" : "Billing context"}</label>)}</CardContent></Card> : null}
    {visible.overview ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card><CardHeader><CardDescription>Open cases</CardDescription><CardTitle className="text-3xl">{metrics.open}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Customer issues in the queue</p></CardContent></Card><Card><CardHeader><CardDescription>High priority</CardDescription><CardTitle className="text-3xl">{metrics.highPriority}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Needs quick attention</p></CardContent></Card><Card><CardHeader><CardDescription>Unassigned</CardDescription><CardTitle className="text-3xl">{metrics.unassigned}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Waiting for an owner</p></CardContent></Card><Card><CardHeader><CardDescription>In progress</CardDescription><CardTitle className="text-3xl">{metrics.inProgress}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Being worked now</p></CardContent></Card><Card><CardHeader><CardDescription>Escalated</CardDescription><CardTitle className="text-3xl">{metrics.escalated}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Requires supervision</p></CardContent></Card></div> : null}
    {visible.priority ? <Card><CardHeader><CardTitle>Priority queue</CardTitle><CardDescription>Cases that should guide today&apos;s support work.</CardDescription></CardHeader><CardContent className="space-y-3">{requests.filter((request) => request.priority === "critical" || request.priority === "high").slice(0, 5).map((request) => <Link key={request.id} href={`/requests/${request.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3 hover:bg-muted/50"><div><p className="font-medium">{request.title}</p><p className="text-sm text-muted-foreground">{request.customer.name} · {getCaseReference(request.id)}</p></div><div className="flex items-center gap-2"><Badge variant="danger">{formatCaseLabel(request.priority)}</Badge><Badge variant="warning">{formatCaseLabel(request.status)}</Badge></div></Link>)}{requests.filter((request) => request.priority === "critical" || request.priority === "high").length === 0 ? <p className="text-sm text-muted-foreground">No high priority cases right now.</p> : null}</CardContent></Card> : null}
    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">{visible.recent ? <Card><CardHeader><CardTitle>Recent cases</CardTitle><CardDescription>Latest customer issues entering or moving through the queue.</CardDescription></CardHeader><CardContent className="space-y-3">{requests.slice(0, 5).map((request) => <Link key={request.id} href={`/requests/${request.id}`} className="flex items-center justify-between gap-4 border-b border-border py-3 last:border-0"><div><p className="font-medium">{request.title}</p><p className="text-sm text-muted-foreground">{request.customer.name}</p></div><div className="text-right"><p className="text-sm capitalize">{formatCaseLabel(request.status)}</p><p className="text-xs text-muted-foreground">{new Date(request.updatedAt).toLocaleDateString()}</p></div></Link>)}</CardContent></Card> : null}{visible.transactions ? <Card><CardHeader><CardTitle>Billing context</CardTitle><CardDescription>Recent transactions for customer conversations.</CardDescription></CardHeader><CardContent className="space-y-3">{transactions.slice(0, 5).map((transaction) => <div key={transaction.id} className="flex items-center justify-between gap-4 border-b border-border py-3 last:border-0"><div><p className="font-medium">{transaction.description}</p><p className="text-sm text-muted-foreground">{transaction.customer?.name ?? "Customer"}</p></div><p className={transaction.type === "income" ? "text-emerald-600" : "text-red-600"}>{new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(transaction.amount)}</p></div>)}</CardContent></Card> : null}</div>
  </div>;
}